export const couponTemplate = {
  version: '2026-06-24-a',
  campaignName: 'MOSSA Sport Society',
  branchLabel: 'สาขาศรีระยอง',
  logoText: 'MOSSA',
  logoUrl: '',
  title: 'คูปองทดลองฟรี 1 วัน',
  subtitle: 'เข้าใช้บริการ MOSSA Sport Society ฟรี 1 วัน',
  bodyText: 'แสดงคูปองนี้กับพนักงานก่อนเข้าใช้บริการ สิทธิ์จะสมบูรณ์เมื่อพนักงานตรวจสอบและกดยืนยันใช้สิทธิ์ในระบบ',
  badgeText: 'FREE TRIAL',
  primaryColor: '#0f766e',
  accentColor: '#14b8a6',
  backgroundColor: '#f8fafc',
  textColor: '#0f172a',
  expiresLabel: 'ใช้ได้ถึง',
  terms: [
    'ใช้ได้ 1 ครั้งต่อ 1 คน',
    'สำหรับลูกค้าใหม่หรือผู้ที่ MOSSA กำหนดเท่านั้น',
    'ไม่สามารถแลกเปลี่ยนเป็นเงินสดได้',
    'ระบบหลังบ้านเป็นตัวตัดสินสถานะการใช้งานจริง',
  ],
  showQrCode: false,
  showBarcode: true,
};
